### ISSUE TITLE
Running into segfault

### ISSUE THREAD

**Issue by RayCPreston** [uhcs2320/hw01#1]
So git seems like it functions as a forum among the people in the group, if this is not an appropriate place to post personal problems with code, please let me know and pull it down, but this frustration is getting to me, and maybe I could help someone else in addition to myself.

Anyway, to the point, I have made a class for the linked list, and everything works as designed except for the consolidateList function i wrote: it is causing a segfault.  This only happens when I include the deleteNode() function in the consolidateList() function.  Without the deleteNode() function it does exactly what I intend, as does delete node, when called regularly.  I understand that segfaults are tied to abusing memory, but I can't get this to go away.  I will only post the relevant functions and the snippit of code that uses it.   Apologies in advance for the formatting of this post

void List::deleteNode(string deleteID){
    nodePtr delPtr = NULL;
    temp = head;
    curr = head;
    while(curr != NULL && curr->ID.compare(deleteID) != 0){
        temp = curr;
        curr = curr->next;
    }
    if(curr == NULL){
        cout << deleteID << "was not in the list." << endl;
        delete delPtr;
    }
    else{
        delPtr = curr;
        curr = curr->next;
        temp->next = curr;
        if(delPtr == head){
            head = head->next;
            temp = NULL;
        }
        delete delPtr;
    }
}
void List::consolidateList(){
    nodePtr n = new node;
    n->next = NULL;
    string nameComp, appNoti, appID, currNotification, currID;
    curr = head;
    while(curr != NULL){
        nameComp = curr->name;
        currNotification = curr->notification;
        currID = curr->ID;
        n = curr;
        n = n->next;
        while(n != NULL){
            if(n->name.compare(nameComp) == 0){
                appNoti = n->notification;
                currNotification.append(appNoti);
                curr->notification = currNotification;
                appID = n->ID;
                currID.append(appID);
                curr->ID = currID;
                List::deleteNode(appID);  
                n = n->next;
            }
            else{
                n = n->next;
            }  
        }
        curr = curr->next;
    }
    delete n;  
}
from main()
while(getline(inData, line)){
            ss << line;
            ss >> tempName;
            ss >> tempNotification;
            ss >> tempID;
            if(line[0] != '#'){
                email.addNode(tempName, tempNotification, tempID);
                ss.clear();
            }
            else{}  
        }

**Comment by aleman** [comment]
It is very difficult to read someone's C++ code. I only spotted a `delete delPtr` inside the `if` block on "was not in the list". Any delete to a null pointer will likely cause trouble.

Git is for software version control. The "issues" part is somewhat similar to a forum, yes.

**Comment by NeoISE** [comment]
Three things could have occurred:
1. Messing with a null pointer (i.e. changing nonexistent properties)
2. Messing with an uninitialized pointer (from your code, this might not be the case)
3. Messing with a pointer that points to a "deleted" object; if the object pointed to is already deleted off of  heap or removed off of the stack, don't touch it.

**Comment by vlykarye** [comment]
For deleting memory, please set pointers to 0.

![image](http://i.imgur.com/fNMLaZq.png)

**Comment by NeoISE** [comment]
@vlykarye, deleting a null pointer is "safe":

``` C++
int * ptr = NULL;
delete ptr;             // No error/exception
ptr = NULL;             // Always NULLify deleted pointers
```

There is no need to check for the non-NULL address, modern compiler will most-likely do this check anyways.

**Comment by vlykarye** [comment]
My mistake. The error is from deleting twice and the pointer pointing to de-allocated memory. So the non-null check is definitely pointless.

> My 2015 visual studio compiler throws corrupted heap exceptions when doing so. Up to you what you want to do, but I find that good practice is good practice. Being efficient is for coding, not lazy. (I think it's lazy to skip steps because the compiler should optimize it away. That's simply my opinion though.) -- my bad reply

**Comment by vlykarye** [comment]
Oh, I see what you are saying. Yes, deleting a null pointer should be safe. I suppose the more important step is setting them to 0 afterwards.

**Comment by NeoISE** [comment]
@vlykarye, how are you getting an error on deleting a `NULL` pointer? I have never gotten an error, even on VS2015.

**Comment by vlykarye** [comment]
@NeoISE No, I mistook the error for trying to access invalid memory as an error for trying to delete a null pointer. I'm not sure why I thought about it that way. It doesn't make sense.

**Comment by RayCPreston** [comment]
So for those of you still looking to see why this was happening, I figured the answer out a couple of days back, sorry for not updating the situation.  So essentially, the list does not update when it returns to the consolidateList() function from the deleteNode() function.  Therefore, curr = curr->next eventually will pass to a value that was deleted from the list and is now NULL.  This was remedied by refreshing the list with a while loop that states:

curr = head;
    while(curr->ID != appID){
    curr = curr->next;
    }

This will update the curr pointer to the point just past the node that was deleted, assuming n did not find any other related nodes for deletion.

**Comment by aleman** [comment]
I'll close this, but please re-open it if there are further questions.
