### ISSUE TITLE
Test-Cases

### ISSUE THREAD

**Issue by ShortCircuit865** [uhcs2320/hw01#11]
**Test Cases g - t do NOT have output files posted and some of these test cases contain multiple files which means manually checking if the output is correct is quite laborious and prone to error.**

**Comment by C3M20** [comment]
I just uploaded the output files

**Comment by ShortCircuit865** [comment]
Ninja Edit: Test Cases i and j are still missing output files
![screenshot 18](https://cloud.githubusercontent.com/assets/22581526/19026256/1c9086b8-88e9-11e6-86f4-c52e83666834.png)

//Thank You
