### ISSUE TITLE
No one answering emails....

### ISSUE THREAD

**Issue by MoJoShMaN** [uhcs2320/hw01#4]
I have been trying to contact the account representative (miller@cs.uh.edu as stated in class) for several days now and have not gotten a response back.  I cannot sign into linux to upload hw without account help.  What do I do?

**Comment by aleman** [comment]
Try stopping by on Monday at her office (just a few doors from the CS department main office).
Or give her a call (number should be listed in the department's website, of via UH-search).
(Both options worked for other students in the past).

**Comment by MoJoShMaN** [comment]
I have continued to try to contact her. No response yet, I'm otw to school,
though I live in conroe. Will let u know when she gets back to me.going
straight to her office

**Comment by MoJoShMaN** [comment]
I've finally gotten a hold of her. She said she was out on vacation.....
I'm cutting it close to the 10 am deadline. I'm going to send u copy of my
cpp file so u know I'm trying to weasel you out of extra time. Hopefully I
will get this is before 10 though.
