### ISSUE TITLE
Purchase-order

### ISSUE THREAD

**Issue by doanHa** [uhcs2320/hw01#5]
If a **purchase-order** does not have any followed **purchase-order-cancellation**, but there is a **purchase-order-revise** after it (either immediately or after some lines), should the **purchase-order** be taken out and replace by the **purchase-order-revise** regardless of the person? Or do we keep both? Or do we keep the **purchase-order**?

**Comment by aleman** [comment]
Keep both. 
By the way, thanks, this is a good idea for a test case.
