### ISSUE TITLE
Segmentation Fault(core dumped) error

### ISSUE THREAD

**Issue by doanHa** [uhcs2320/hw01#7]
Whenever I run the program, I would get this run-time-error after the first file, when I try to combine notification on the second file. I have no idea why this is happening, because the code work just fine for the first file, and not the second nor third. Help please?

**Comment by aleman** [comment]
It could be due to variables set somewhere. On second or third file, such variables may need to be initialized again.

**Comment by aleman** [comment]
I'll close this, but please re-open it if there are further questions.
