### ISSUE TITLE
Global Combinations

### ISSUE THREAD

**Issue by vlykarye** [uhcs2320/hw01#8]
This may seem a bit late, but it was just pointed out to me by a friend.
You tell us to combine files independently of each other, resulting in a message that can contain multiple parts separated by ", " (comma, space). Then, we are to combine these notifications from each file into one global list. You do not, however, say if we should consider each part of the message or the message as a whole when combining files into the global list. For instance, say result of file 1 is:
Meredith   Invoice  PARK-1203, PARK-1205, TECH-3034
and file 2 is:
Meredith   Invoice  PARK-8888, PARK-1205, TECH-3034

If we combine the notifications as a whole, then the result would be:
Meredith   Invoice  PARK-1203, PARK-1205, TECH-3034, PARK-8888, PARK-1205, TECH-3034

If we combine them separately, then:
Meredith   Invoice  PARK-1203, PARK-1205, TECH-3034, PARK-8888
or something similar.

I wanted to point this out because I AM NOT going to figure out how to combine the files separately when making the global list.

> Global list of all input files: Once every input file has had its notifications combined (independently of the other input files), a global list of notifications will be created by taking one notification at a time of each of the input files.
> 
> Example:
> 
> File 1 has notifications A B C D
> 
> File 2 has notifications G H K
> 
> File 3 has notifications M N
> 
> File 4 has notifications Q R T S
> 
> The global list would be: A G M Q B H N R C K T D S
> 
> The final step is to combine the global list of notifications. For example, if file 1 has a notification Alex Invoice PEDS-765, and file 4 has a notification Alex Invoice PSYCH-3654, then such notifications need to be combined into only one notification: Alex Invoice PEDS-765, PSYCH-3654

You give great examples on how to combine files individually, and I appreciate that. However, too little information/examples are given for how to combine files into the global list. At this point, I don't have the time or willpower to change this, and I do not believe it is my responsibility to be able to know if I understand the assignment properly or not. The way I understood the assignment the first time seemed correct to me, but now I'm not sure. Test cases would be useful in these situations.

Also, as far as I know, our grades have not been given to us. It has been 2 or 3 week. I would like to know how I did on the first assignment before turning in the second.

**Comment by aleman** [comment]
1.
There will no be test cases for the example you showed:
File 1's combined list is:
Meredith Invoice PARK-1203, PARK-1205, TECH-3034
and file 2's combined list is:
Meredith Invoice PARK-8888, PARK-1205, TECH-3034

However, the following is a valid test case:
File 1's combined list is:
Meredith Invoice PARK-1203
and file 2's combined list is:
Meredith Invoice PARK-8888

2.
We talked about combining lists into the global list in class.
The global list is created by taking one node at a time from each list.
1. It is OK if your solution to the assignment does not handle some functionality such as multiple files. You'll likely get partial credit on other aspects.
2. Grades: We were trying for a more efficient way to provide the grades via the linux system directly.
   On next class I can give you your grade for hw0.
   The test cases (with expected output) were provided almost a week ago. We mentioned in class that any one can run the test cases to see which one failed (if any).

**Comment by vlykarye** [comment]
Fair enough for point 2.
For point 1, I'll trust that there are no test cases like this.

Thanks.

**Comment by aleman** [comment]
I'll close this, but please re-open it if there are further questions.
